apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: mhav
  namespace: { { .Values.namespace } }
spec:
  ingressClassName: traefik
  rules:
    - host: { { .Values.ingress.host } }
      http:
        paths:
          - backend:
              service:
                name: mhav
                port:
                  number: 80
            path: /
            pathType: Prefix
