apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecureproxy
  name: mhav
spec:
  ingressClassName: traefik
  rules:
    - host: megisholavonat.info
      http:
        paths:
          - backend:
              service:
                name: mhav
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: mhav-api
                port:
                  number: 80
            path: /api
            pathType: Prefix
