apiVersion: v1
kind: Service
metadata:
  name: mhav
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mhav
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
