apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/auth-type: basic
    traefik.ingress.kubernetes.io/auth-secret: mhav-dev-basic-auth-secret
  name: mhav-dev
spec:
  ingressClassName: traefik
  rules:
    - host: mhav-dev.localhost
      http:
        paths:
          - backend:
              service:
                name: mhav-dev
                port:
                  number: 80
            path: /
            pathType: Prefix
