apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: mhav-dev-basic-auth@kubernetescrd
  name: mhav-dev
spec:
  ingressClassName: traefik
  rules:
    - host: dev.megisholavonat.info
      http:
        paths:
          - backend:
              service:
                name: mhav-dev
                port:
                  number: 80
            path: /
            pathType: Prefix
