apiVersion: apps/v1
kind: Deployment
metadata:
  name: mhav
spec:
  selector:
    matchLabels:
      app: mhav
  template:
    metadata:
      labels:
        app: mhav
    spec:
      containers:
        - name: mhav
          image: ghcr.io/megisholavonat/megisholavonat:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
