apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: tile-cache
spec:
  ingressClassName: traefik
  rules:
    - host: tc.megisholavonat.info
      http:
        paths:
          - backend:
              service:
                name: tile-cache
                port:
                  number: 80
            path: /
            pathType: Prefix
