apiVersion: v1
kind: Service
metadata:
  name: tile-cache
  labels:
    app: tile-cache
    component: tile-cache
spec:
  selector:
    app: tile-cache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
